name: Daily Twitter Scraper

on:
  schedule:
    - cron: '0 8 * * *'   # runs every day at 8:00 UTC
  workflow_dispatch:       # allows manual run from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pandas snscrape==0.7.0.20230622

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tweets_*.csv
          git commit -m "Add scraped tweets on $(date)" || echo "No changes"
          git push
          
