name: Twitter Scraper Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:        # Allows manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      - name: Commit results if updated
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Check if there are changes before committing
          if [[ `git status --porcelain` ]]; then
            git add tweets.csv
            git commit -m "Update scraped tweets $(date)"
            git push
          else
            echo "No new tweets to commit."
          fi
